### ISSUE TITLE
can not reproduce the main-naive result?

### ISSUE THREAD

**Issue by LeoCho1learning** [ppwwyyxx/RAM-multiprocess-dataloader#1]
hi, your blog helped me a lot, thanks.

but i cant reproduce the main-naive result.
in my case, the USS reached ~226M and stopped which didnt go up to 1.8G in your log. can you please tell me why? 

time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86396  14650  2.7G   793.4M  307.7M  2.4G      17.8M
 86396  14779  2.6G   684.6M  198.5M  2.4G      17.4M
 86396  14780  2.6G   684.6M  198.4M  2.4G      17.4M
 86396  14781  2.6G   685.0M  198.9M  2.4G      17.4M
 86396  14782  2.6G   686.0M  200.2M  2.4G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86397  14650  2.7G   797.2M  312.5M  2.4G      17.8M
 86397  14779  2.6G   688.5M  203.3M  2.4G      17.4M
 86397  14780  2.6G   688.5M  203.2M  2.4G      17.4M
 86397  14781  2.6G   688.8M  203.7M  2.4G      17.4M
 86397  14782  2.6G   689.8M  205.0M  2.4G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86398  14650  2.7G   801.2M  317.5M  2.4G      17.8M
 86398  14779  2.6G   692.5M  208.3M  2.4G      17.4M
 86398  14780  2.6G   692.4M  208.2M  2.4G      17.4M
 86398  14781  2.6G   692.8M  208.7M  2.4G      17.4M
 86398  14782  2.6G   693.8M  209.9M  2.4G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86399  14650  2.7G   805.1M  322.4M  2.4G      17.8M
 86399  14779  2.6G   696.3M  213.1M  2.4G      17.4M
 86399  14780  2.6G   696.4M  213.1M  2.4G      17.4M
 86399  14781  2.6G   696.7M  213.6M  2.4G      17.4M
 86399  14782  2.6G   697.7M  214.8M  2.4G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86400  14650  2.7G   809.0M  327.3M  2.4G      17.8M
 86400  14779  2.6G   700.3M  218.1M  2.4G      17.4M
 86400  14780  2.6G   700.3M  218.0M  2.4G      17.4M
 86400  14781  2.6G   700.7M  218.6M  2.4G      17.4M
 86400  14782  2.6G   701.6M  219.7M  2.4G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86402  14650  2.7G   813.0M  332.3M  2.3G      17.8M
 86402  14779  2.6G   704.2M  223.0M  2.4G      17.4M
 86402  14780  2.6G   704.3M  222.9M  2.4G      17.4M
 86402  14781  2.6G   704.6M  223.5M  2.4G      17.4M
 86402  14782  2.6G   705.5M  224.7M  2.3G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86403  14650  2.7G   815.7M  335.9M  2.3G      17.8M
 86403  14779  2.6G   707.0M  226.6M  2.3G      17.4M
 86403  14780  2.6G   706.9M  226.5M  2.3G      17.4M
 86403  14781  2.6G   706.9M  226.5M  2.3G      17.4M
 86403  14782  2.6G   706.9M  226.3M  2.3G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86404  14650  2.7G   815.7M  335.9M  2.3G      17.8M
 86404  14779  2.6G   707.0M  226.6M  2.3G      17.4M
 86404  14780  2.6G   706.9M  226.5M  2.3G      17.4M
 86404  14781  2.6G   706.9M  226.5M  2.3G      17.4M
 86404  14782  2.6G   706.9M  226.3M  2.3G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86405  14650  2.7G   815.7M  335.9M  2.3G      17.8M
 86405  14779  2.6G   707.0M  226.6M  2.3G      17.4M
 86405  14780  2.6G   706.9M  226.5M  2.3G      17.4M
 86405  14781  2.6G   706.9M  226.5M  2.3G      17.4M
 86405  14782  2.6G   706.9M  226.3M  2.3G      17.4M
  time    PID  rss    pss     uss     shared    shared_file
------  -----  -----  ------  ------  --------  -------------
 86406  14650  2.7G   815.7M  335.9M  2.3G      17.8M
 86406  14779  2.6G   707.0M  226.6M  2.3G      17.4M
 86406  14780  2.6G   706.9M  226.5M  2.3G      17.4M
 86406  14781  2.6G   706.9M  226.5M  2.3G      17.4M
 86406  14782  2.6G   706.9M  226.3M  2.3G      17.4M

**Comment by ppwwyyxx** [comment]
I don't know whether the logs provided above is full logs or not. 

If you provided full logs, then your log is much much shorter than the one in the repo. You need to run the code for longer, e.g. a few minutes.

If you already run it long enough and provided only the end of logs and observing different results from the one in the repo, please provide a docker container such that other people can reproduce your results.
The results in the repo can be reproduced in the official pytorch docker container  pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime .

**Comment by ppwwyyxx** [comment]
No response, closing..

**Comment by korotaS** [comment]
Hi! 
I had similar issue when trying to reproduce the naive result and `uss` also stuck at ~ 226M (Debian 11, python 3.8, pytorch 13.1). When I ran the same code in `pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime` docker container, it reproduced perfectly. So I did a little ablation study and noticed, that the results reproduced only in those containers where python version is above 3.10 (for example, using images `python:3.10` or `pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime`). 
So can this problem (about using too much RAM) be caused by some python-related issue?

**Comment by ppwwyyxx** [comment]
Thanks for the report. This is because python<3.10 has a bug where pickle does not increment object refcount when reading the objects.

In reality, user's dataloader should increment object refcount. So I changed pickle to msgpack for python<3.10 in https://github.com/ppwwyyxx/RAM-multiprocess-dataloader/commit/79897b26a2c4185a3ed086f18be5ea300913d5b7 and now the results should be reproducible for python<3.10 as well.

**Comment by korotaS** [comment]
Thanks! Now it reproduces on python 3.8.
