### ISSUE TITLE
Reproducing the results with a `torch.utils.data.DataLoader`?

### ISSUE THREAD

**Issue by FabianSchuetze** [ppwwyyxx/RAM-multiprocess-dataloader#2]
Thanks for this wonderful repo. It's a pleasure to work with it and very educational. 

Is there a possibility to obtains the process ids from a a `torch.utils.data.DataLoader` instance? For example, with 
```
ds = NaiveDatasetFromList(create_coco())
loader = torch.utils.data.DataLoader(ds, num_workers=4)
```
Could I infer the process ids to replicate the memory usage table you created?

**Comment by ppwwyyxx** [comment]
After the dataloader has started, the pid should be available in `[x.pid for x in loader._iterator._workers]`. You can refer to its source code for details.

**Comment by FabianSchuetze** [comment]
Thanks for the comment - very much appreciated.
