### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by roachsinai** [ppwwyyxx/RAM-multiprocess-dataloader#3]
Get `TypeError` when import common.py. Seems code at https://github.com/ppwwyyxx/RAM-multiprocess-dataloader/blob/main/common.py#L11 should be change to

`def get_mem_info(pid: int) -> Dict[str, int]:`

and others:

```
-  def __init__(self, pids: list[int]=None):
+  def __init__(self, pids: List[int]=None):

-def create_coco() -> list[Any]:
+def create_coco() -> List[Any]:
```

**Comment by ppwwyyxx** [comment]
The annotation is correct if you use python >= 3.9

Latest commit https://github.com/ppwwyyxx/RAM-multiprocess-dataloader/commit/aa4751bb449eb8ddf14375cd545d5c941ee121c9 adds support for python 3.7 & 3.8 as well.

**Comment by roachsinai** [comment]
Thanks for pointing this!
